idf_component_register(
    SRCS
        "wifi_manager.c"
        "wifi_manager_ap_policy.c"
        "wifi_manager_profile_policy.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        esp_event
        esp_netif
        esp_timer
        esp_wifi
        freertos
        lwip
        wifi_profiles
)
